model_type: yolov8n.pt
pretrained: True
seed: 0
imgsz: 640 
batch: 16
epochs: 5
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.0001  # learning rate 
name: 'yolov8n_exp_v1' # experiment name